Update matrix-static.yml

diff --git a/.github/workflows/matrix-static.yml b/.github/workflows/matrix-static.yml
--- a/.github/workflows/matrix-static.yml
+++ b/.github/workflows/matrix-static.yml
@@ -40,4 +40,6 @@ jobs:
       - name: Simulate deployment
         run: |
           echo "Deploying app built with node ${{ matrix.node-version }} on ${{ matrix.os }}"
-          if [ "${{ matrix.node-version }}" == "16" ]; then exit 1; fi
+          if [ "${{ matrix.node-version }}" == "18" ]; then exit 1; fi
+          echo "Sleeping to give other jobs time to be visibly in-progress when this one fails..."
+          sleep 20
